Vagrant.configure("2") do |config|
  config.ssh.forward_x11 = true
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network "forwarded_port", guest: 2323, host: 2323
  config.vm.network "forwarded_port", guest: 3391, host: 3391
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", 2048]
  end
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install xauth gdebi-core -y
     python3 /vagrant/scripts/install.py
   SHELL
end
